import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
         <nav className="bg-white shadow-md mb-6 p-4 flex gap-4 justify-center">
            <a href="/" className="text-blue-600 hover:underline font-medium">Planning</a>
            <a href="/medecins" className="text-blue-600 hover:underline font-medium">Médecins</a>
            <a href="/patient" className="text-blue-600 hover:underline font-medium">Patients</a>
         </nav>
         {children}
      </body>
    </html>
  );
}
